name: Actualizar

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Actualizar
        run: |
         ./update.py
      - name: Commit
        run: |
          git config --global user.email "reportes_mhe@example.com"
          git config --global user.name "reportes_mhe-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualizaci√≥n de reportes"; git push -q "https://$GH_TOKEN@github.com/mauforonda/reportes_mhe.git" main)
